[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags =
    -D USB_SERIAL
    -include Arduino.h
monitor_speed = 115200


lib_deps =
    sparkfun/SparkFun u-blox GNSS v3@^3.1.9
    sparkfun/SparkFun Qwiic 6Dof - LSM6DSO@^1.0.2

    ## All 3 needed for BMP280 altimeter
    adafruit/Adafruit BMP280 Library@^2.6.8
    adafruit/Adafruit Unified Sensor@^1.1.14
    adafruit/Adafruit BusIO@^1.16.1

    ## Radio
    xreef/EByte LoRa E32 library@^1.5.13

    ## Magnetometer
    https://github.com/tedyapo/arduino-MLX90393.git
